##NUMPY AND ARRAY BESICS

In [1]:
import numpy as np

#creating array from list

In [2]:
arr_1D = np.array([1,2,3,7.8,"hi"])
print(f"1D array is :{arr_1D}")
print("1D array is :",arr_1D)
arr_2D =np.array([[1,2,3],[3,5,6]])
print("2D array is : ",arr_2D)


1D array is :['1' '2' '3' '7.8' 'hi']
1D array is : ['1' '2' '3' '7.8' 'hi']
2D array is :  [[1 2 3]
 [3 5 6]]


In [3]:
list_1 = [1,2,3,7.8,"hi"]
arr_1D = np.array(list_1)
print(f"1D array is :{arr_1D}")
print("1D array is :",arr_1D)
arr_2D =np.array([[1,2,3],[3,5,6]])


1D array is :['1' '2' '3' '7.8' 'hi']
1D array is : ['1' '2' '3' '7.8' 'hi']


### List vs Numpy array

In [4]:
py_list = [1,2,3,6.7,"hi"]
print("Python List multiplication :",py_list*2)

np_array = np.array([1,2,3,7.8])
print("numpy array multiplication :",np_array*2)

Python List multiplication : [1, 2, 3, 6.7, 'hi', 1, 2, 3, 6.7, 'hi']
numpy array multiplication : [ 2.   4.   6.  15.6]


In [5]:
import time
start = time.time()
py_list = [i*2 for i in range(2000000)]
list_time  = time.time() - start
print(list_time)
start = time.time()
np_array = np.arange(2000000)*2
arr_time = time.time() - start
print(arr_time)


0.14789223670959473
0.01411294937133789


#### Create array from scratch

In [6]:
arr_all_zero = np.zeros((3,4))
print(arr_all_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
arr_all_ones = np.ones((3,3))
print(f"the array is \n{arr_all_ones}")

the array is 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# use full to create array of any number 
# use full to construct all 
arr_any_number = np.full((5,7),0)
print(f"the array is : \n{arr_any_number}")
arr_any_number1 = np.full((51,72),109)
print(f"the array is : \n{arr_any_number1}")


the array is : 
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
the array is : 
[[109 109 109 ... 109 109 109]
 [109 109 109 ... 109 109 109]
 [109 109 109 ... 109 109 109]
 ...
 [109 109 109 ... 109 109 109]
 [109 109 109 ... 109 109 109]
 [109 109 109 ... 109 109 109]]


In [9]:
#random array
arr_random = np.random.random((3,8))
print(f"the random array is : \n{arr_random}")

the random array is : 
[[0.89213172 0.2207981  0.76675521 0.16780063 0.98598844 0.56214187
  0.66314679 0.77645785]
 [0.31109926 0.00870291 0.15868012 0.72661456 0.99210261 0.91260571
  0.24370035 0.75553978]
 [0.70474551 0.15842034 0.66188282 0.60677953 0.86620101 0.13108347
  0.67895774 0.23896741]]


In [10]:
#sequence array
arr_seq = np.arange(2,19,5)# 2 ia start 19 is end 5 is jump
print(f"the array is : \n{arr_seq}")

the array is : 
[ 2  7 12 17]


In [11]:
#sequence array
arr_seq = np.arange(2,19)# 2 ia start 19 is end 
print(f"the array is : \n{arr_seq}")

the array is : 
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


#Vector Matrix Tensor

In [12]:
vector = np.array([1,2,3,4,5,"ji"])
print(f"the array is : \n{vector}")

the array is : 
['1' '2' '3' '4' '5' 'ji']


In [13]:
matrix = np.array([[1,2,3],[1,2,3],[3,5,1]])
print(f"the array is : \n{matrix}")

the array is : 
[[1 2 3]
 [1 2 3]
 [3 5 1]]


In [14]:
#tensor
tensor = np.array([[[1,2,3],[1,2,3],[3,5,1]],[[1,3,4],[5,6,7],[7,8,9]]])
print(f"the array is : \n{tensor}")

the array is : 
[[[1 2 3]
  [1 2 3]
  [3 5 1]]

 [[1 3 4]
  [5 6 7]
  [7 8 9]]]


##ARRAY PROPERTIES

In [15]:
array = np.array([[[1,2,3],[1,2,3],[3,5,1]],[[1,3,4],[5,6,7],[7,8,9]]])
print(f"the array is : \n{tensor}")

print("array shape :",array.shape)
print("array dimention :",array.ndim)
print("array size :",array.size)
print("array data type :",array.dtype)
print(type(array))

the array is : 
[[[1 2 3]
  [1 2 3]
  [3 5 1]]

 [[1 3 4]
  [5 6 7]
  [7 8 9]]]
array shape : (2, 3, 3)
array dimention : 3
array size : 18
array data type : int64
<class 'numpy.ndarray'>


Array Reshape

In [16]:
arr = np.arange(34)
print(f"the array is : \n{arr}")

reshaped = arr.reshape((2,17))
print(f"the  reshaped array is : \n{reshaped}")

flattened = reshaped.flatten()
print(f"the array is : \n{flattened}")

#ravel() return view of reshaped array instead of copy or ravel dont change the array just return the view 
raveled = reshaped.ravel()
print(f"the array is : \n{raveled}")

transposed = reshaped.T
print(f"the array is : \n{transposed}")
 

the array is : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33]
the  reshaped array is : 
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33]]
the array is : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33]
the array is : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33]
the array is : 
[[ 0 17]
 [ 1 18]
 [ 2 19]
 [ 3 20]
 [ 4 21]
 [ 5 22]
 [ 6 23]
 [ 7 24]
 [ 8 25]
 [ 9 26]
 [10 27]
 [11 28]
 [12 29]
 [13 30]
 [14 31]
 [15 32]
 [16 33]]


In [17]:
arr = np.array([1,2,35,1,2,34])
print(arr.max())

import numpy as np

arr = np.array([1, 2, 3, 2, 4])

new_arr = arr[arr != 2]

print(new_arr)  # [1 3 4]


35
[1 3 4]


In [18]:
new_arr = np.delete(arr, 1)  # removes element at index 1
print(new_arr)


[1 3 2 4]


In [19]:
new_arr = np.delete(arr, [1, 3])
new_arr

array([1, 3, 4])

In [20]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

new_arr = np.delete(arr, 1, axis=0)  # remove row 1
new_arr

array([[1, 2],
       [5, 6]])