## NUMPY ARRAY OPERATION

In [1]:
import numpy as np

In [2]:
arr =np.arange(50)
#slicing
print("slicing :",arr[3:7])
# slicing with step 
print("slicing :",arr[-3:-34:-3])

#negetive indexing 
print("slicing :",arr[-4]) # print 4th element from last

slicing : [3 4 5 6]
slicing : [47 44 41 38 35 32 29 26 23 20 17]
slicing : 46


In [3]:
arr_2d = np.array([[1,2,3],
                   [3,2,1],
                   [7,5,9]
                    ])
#print specific element 
print("The specific element is in 2nd row 1st column is : ",arr_2d[1,0])

The specific element is in 2nd row 1st column is :  3


In [4]:
arr_2d = np.array([[1,2,3],
                   [3,2,1],
                   [7,5,9],
                   [3,8,5]
                    ])
#print entire row
print("The entire row  : ",arr_2d[2]) #2nd row 
print("The entire column  : ",arr_2d[:,1]) #2nd column 


The entire row  :  [7 5 9]
The entire column  :  [2 2 5 8]


# SORTING

In [5]:
unsorted_array = np.array([4,3,5,6,1,7,8,9,3])
sorted_array = np.sort(unsorted_array)
print(f"the sorted array is : {sorted_array}")


the sorted array is : [1 3 3 4 5 6 7 8 9]


In [6]:
unsorted_array_2d = np.array([[1,2,3],
                   [3,2,1],
                   [7,5,9],
                   [3,8,5]
                    ])
# sort 2d array by column use axis value 0
unsorted_array_2d = np.sort(unsorted_array_2d,axis=0)
print(f"the sorted array is : {unsorted_array_2d}")

the sorted array is : [[1 2 1]
 [3 2 3]
 [3 5 5]
 [7 8 9]]


In [7]:
unsorted_array_2d = np.array([[1,2,3],
                   [3,2,1],
                   [7,5,9],
                   [3,8,5]
                    ])
# sort 2d array by row use axis value 1
unsorted_array_2d = np.sort(unsorted_array_2d,axis=1)
print(f"the sorted array is : {unsorted_array_2d}")

the sorted array is : [[1 2 3]
 [1 2 3]
 [5 7 9]
 [3 5 8]]


## FILTER ARRAY

In [8]:
numbers = np.array([2,4,3,4,5,6,4,3,6])
print(f"the element in 4th index is :{numbers[3]}")
#print the even numbers in the array
even_numbers = numbers[numbers%2==0]
print("even elements are :",even_numbers)
sort_even_numbers = even_numbers.sort()
print(f"even elements are sorted :{np.sort(even_numbers)}")


the element in 4th index is :4
even elements are : [2 4 4 6 4 6]
even elements are sorted :[2 4 4 4 6 6]


#### MASK

In [9]:
numbers = np.array([32,4,37,4,5,6,4,3,6,34,23,45,12,78,56,34,23,58,51,27,93])
mask = numbers >= 10
print(f"numbers that are greater than equal to 10 :{numbers[mask]}")

numbers that are greater than equal to 10 :[32 37 34 23 45 12 78 56 34 23 58 51 27 93]


# fancy indexing vs np.where

In [10]:
numbers = np.array([32,4,37,4,5,6,4,3,6,34,23,45,12,78,56,34,23,58,51,27,93])
indices = [0,5,6]
print(numbers[indices])


[32  6  4]


In [11]:
numbers_array = np.array([32,4,37,4,5,6,4,3,6,34,23,45,12,78,56,34,23,58,51,27,93])
mask = np.where(numbers_array > 20) # stores the indices where the condition is true
print("the numbers are : ",numbers_array[mask])

the numbers are :  [32 37 34 23 45 78 56 34 23 58 51 27 93]


##### condition

In [12]:
numbers_array = np.array([32,4,37,4,5,6,4,3,6,34,23,45,12,78,56,34,23,58,51,27,93])
condition_array = np.where(numbers_array >=20 , numbers_array * 2 ,numbers_array)
print("the numbers are : ",condition_array)


the numbers are :  [ 64   4  74   4   5   6   4   3   6  68  46  90  12 156 112  68  46 116
 102  54 186]


# ADDING AND REMOVING 

In [13]:
array_1 = np.arange(1,10)
array_2 = np.arange(10,26)
combined_array = np.concatenate((array_1,array_2))
print(combined_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [14]:
# np array
array1 = np.array([1,22,3,4,33])
array2 = np.array([1,1,1,1,1])
sum = print(array1+array2)

[ 2 23  4  5 34]


In [15]:
#normal array
array1 = [1,22,3,4,33]
array2 = [1,1,1,1,1]
sum = print(array1+array2)

[1, 22, 3, 4, 33, 1, 1, 1, 1, 1]


## array compatibility

In [16]:
print(array_1.shape==array_2.shape)
# not compatible 

False


In [17]:

original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print(original)
print("the new array with new row is :\n",with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With new column :\n", with_new_col)


[[1 2]
 [3 4]]
the new array with new row is :
 [[1 2]
 [3 4]
 [5 6]]
With new column :
 [[1 2 7]
 [3 4 8]]


## delete

In [18]:
arr = np.array([1,2,3,4,5,6])
arr_del = np.delete(arr,3,)
print(f"the array after deletation : {arr_del}")


the array after deletation : [1 2 3 5 6]
